name: Analog Mindset
favicon: null
layout_spectrum: 0.39667
typography_spectrum: 0.46305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42240905-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9d9d9'
    - '#767676'
    - '#535353'
    - '#b6b6b6'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
