name: Analog Mindset
favicon: null
layout_spectrum: 0.010706223081797361
typography_spectrum: 0.4852050782646984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.043843096820637584
  lightness: 0.19621335505507886
  saturation: 0.4081442761234939
  rhythmicContrast: 0.03512483346275985
purpose: []
